### ISSUE TITLE
problem with  zoomeye

### ISSUE THREAD

**Issue by devil67** [Warflop/CloudBunny#1]
[+] Looking for target on Shodan...
[+] Looking for target on Censys...
[+] Looking for certificates on Censys...
[+] Looking for target on ZoomEye...
[-] We got an error with your zoomeye credentials. (Check if zoomeye is down ¯\_(ツ)_/¯)

Im registered and checked on zoomeye site but still not work
How can i do?

**Comment by devil67** [comment]
{"error": "bad_request", "message": "SSO Login error, please confirm your email and password", "url": "https://www.zoomeye.org/api"}

**Comment by devil67** [comment]
Sorry work i changed my username with my e-mail :)

**Comment by devil67** [comment]
░░▄░░░▄░▄▄▄▄░░░░░░░░░░░░░░░
░░█▀▄▀█░█▄▄░░░░░░░░░░░░░░░░
░░█░░░█░█▄▄▄░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░
░▄▄▄░▄░░░▄░░▄▄▄░▄▄▄▄▄░░▄▄▄░
█░░░░█░░░█░█░░░░░░█░░░█░░░█
█░▀█░█░░░█░░▀▀▄░░░█░░░█▀▀▀█
░▀▀▀░░▀▀▀░░▄▄▄▀░░░▀░░░▀░░░▀

**Comment by devil67** [comment]
░░░░░▄▄▀▀▀▀▀▀▀▀▀▄▄░░░░░
░░░░█░░░░░░░░░░░░░█░░░░
░░░█░░░░░░░░░░▄▄▄░░█░░░
░░░█░░▄▄▄░░▄░░███░░█░░░
░░░▄█░▄░░░▀▀▀░░░▄░█▄░░░
░░░█░░▀█▀█▀█▀█▀█▀░░█░░░
░░░▄██▄▄▀▀▀▀▀▀▀▄▄██▄░░░
░▄█░█▀▀█▀▀▀█▀▀▀█▀▀█░█▄░

**Comment by devil67** [comment]
Hey bro,can y give some vulnerabily site pls coz i got still this message
 [-] Looks like our rabbit has not gotten so deep. :(

**Comment by Warflop** [comment]
Try this site: http://ctf.hackaflag.com.br
