### ISSUE TITLE
NameError: name 'split_url' is not defined

### ISSUE THREAD

**Issue by t4ktik** [Warflop/cloudbunny#11]
I need help with this error:

_**─# python3 cloudbunny.py -u https://google.es   
Traceback (most recent call last):
  File "/home/t4ktik/tools/cloudbunny/cloudbunny.py", line 187, in <module>
    main()
  File "/home/t4ktik/tools/cloudbunny/cloudbunny.py", line 108, in main
    host = split_url(args.url)
           ^^^^^^^^^
NameError: name 'split_url' is not defined**_

Im using `Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`

**Comment by t4ktik** [comment]
If i try without *.* it gives another error

_**--# python3 cloudbunny.py -u https://google
Hey buddy, pass a real address please!**_

**Comment by Warflop** [comment]
I merged a new version removing the "#!/usr/bin/env python" header. Probably you have python2 and 3 on your env, and the header was redirecting to python2 where there's no "split_url" function.
