### ISSUE TITLE
 No module named 'urlparse'

### ISSUE THREAD

**Issue by maloba1** [Warflop/cloudbunny#7]
C:\pyt\CloudBunny-master>cloudbunny.py -h
Traceback (most recent call last):
  File "C:\pytt\CloudBunny-master\cloudbunny.py", line 6, in <module>
    from urlparse import urlsplit
ModuleNotFoundError: No module named 'urlparse'

C:\pytt\CloudBunny-master>

**Comment by rajeshk28** [comment]
> C:\pyt\CloudBunny-master>cloudbunny.py -h
> Traceback (most recent call last):
> File "C:\pytt\CloudBunny-master\cloudbunny.py", line 6, in
> from urlparse import urlsplit
> ModuleNotFoundError: No module named 'urlparse'
> 
> C:\pytt\CloudBunny-master>

same issue from my side.. can the develpoer help here?????

**Comment by ItsLachy** [comment]
Project is likely dead.

**Comment by JkDevArg** [comment]
Change line 6 for this -> from urllib.parse import urlparse

**Comment by Warflop** [comment]
Fixed on this PR: https://github.com/Warflop/cloudbunny/pull/10
